// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1pD-tdznT18bYas0-lg6gFS1gAt7ZRHo',
    appId: '1:1004073148218:web:bb702183860b0fb4083a03',
    messagingSenderId: '1004073148218',
    projectId: 'fac-loc',
    authDomain: 'fac-loc.firebaseapp.com',
    databaseURL: 'https://fac-loc-default-rtdb.firebaseio.com',
    storageBucket: 'fac-loc.firebasestorage.app',
    measurementId: 'G-TTWB6F24PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaGAnWV8RDAjjX6lU_KgYc26AeQTTJsgQ',
    appId: '1:1004073148218:android:708587a875ae6baf083a03',
    messagingSenderId: '1004073148218',
    projectId: 'fac-loc',
    databaseURL: 'https://fac-loc-default-rtdb.firebaseio.com',
    storageBucket: 'fac-loc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9kG_gvycxe8AdjVrlaEf9UZ651XRcHp8',
    appId: '1:1004073148218:ios:0122fb6c1ae9c90a083a03',
    messagingSenderId: '1004073148218',
    projectId: 'fac-loc',
    databaseURL: 'https://fac-loc-default-rtdb.firebaseio.com',
    storageBucket: 'fac-loc.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );
}
